// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Article struct {
	ID           int32
	Title        string
	Url          string
	Content      sql.NullString
	PublishedAt  sql.NullTime
	Polarity     sql.NullFloat64
	Subjectivity sql.NullFloat64
	Query        sql.NullString
	CreatedAt    sql.NullTime
}
